In [1]:
import numpy as np

In [40]:
A = np.random.rand(24).reshape(6,4)

In [41]:
## QR decomposition
def factorize(A):
    width = A.shape[1]

    Q = np.zeros_like(A)
    R = np.zeros((width,width))

    ## first step
    norm_q = np.linalg.norm(A[:,0])
    Q[:,0] = A[:,0] / norm_q
    R[0,0] = norm_q

    ## gram-schmidts algorithm
    for i in range(1,width):
        Q[:,i] = A[:,i]
        
        for j in range(i):
            Q[:,i] -= np.dot(Q[:,j], A[:,i]) * Q[:,j]
            R[j,i] = np.dot(Q[:,j],A[:,i])

        norm_q = np.linalg.norm(Q[:,i])
        Q[:,i] = Q[:,i] / norm_q
        R[i,i] = norm_q

        ## linearly dependence
        if norm_q == 0:
            print("it has linearly dependent columns")
            break

    return Q, R

In [42]:
Q, R = factorize(A)

In [47]:
print(f"Q: {Q}")
print(f"R: {R}")
print(f"QR: {np.dot(Q,R)}")
print(f"{np.allclose(A, np.dot(Q,R))}")

Q: [[ 0.24094206  0.31780978 -0.13075519  0.82804392]
 [ 0.73495327 -0.40299966  0.09483452 -0.22178094]
 [ 0.16738211  0.66787889  0.03367152 -0.47183967]
 [ 0.28663767 -0.15855325 -0.82485485 -0.04644687]
 [ 0.32658341 -0.17073871  0.53937619  0.19971067]
 [ 0.43006507  0.4860403   0.03825616 -0.02195768]]
R: [[ 1.07456176  0.79163242  1.43894938  0.84350063]
 [ 0.          0.93685567  0.35565569  1.04609791]
 [ 0.          0.          0.3635333  -0.13966025]
 [ 0.          0.          0.          0.49435176]]
QR: [[0.25890713 0.48847945 0.41220043 0.96330121]
 [0.78975268 0.20426032 0.94870694 0.07547403]
 [0.17986242 0.75821122 0.49063003 0.60189628]
 [0.30800988 0.07837016 0.05620453 0.16815516]
 [0.35093404 0.09857648 0.605294   0.12026181]
 [0.46213148 0.79580306 0.80561226 0.85500822]]
True


In [53]:
A = np.random.rand(32).reshape(8,4)
A1 = A[:4,:]
A2 = A[4:,:]
Q1, R1 = factorize(A1)
Q2, R2 = factorize(A2)

In [54]:
print(f"Q1: {Q1}\n")
print(f"Q2: {Q2}\n")
print(f"R1: {R1}\n")
print(f"R2: {R2}")

Q1: [[ 0.68527294 -0.52189049 -0.43087034  0.26903915]
 [ 0.15864133 -0.11512776  0.77049739  0.60655775]
 [ 0.42921514  0.8448833  -0.17325998  0.26819313]
 [ 0.56657593  0.02341213  0.43665261 -0.69841111]]

Q2: [[ 0.55741939  0.66940947 -0.49093721 -0.01245963]
 [ 0.57246786 -0.32283463  0.22802674 -0.71837466]
 [ 0.09695065  0.53301202  0.83425722  0.10253612]
 [ 0.5934347  -0.40443411  0.10487785  0.68794545]]

R1: [[ 1.43572526  0.54612323  1.20003582  0.67214278]
 [ 0.          0.58937456  0.00588519 -0.32400933]
 [ 0.          0.          0.46100505  0.36938417]
 [ 0.          0.          0.          0.57441787]]

R2: [[ 1.55301866  0.93964227  0.57069728  1.1932239 ]
 [ 0.          0.31516227  0.76688191 -0.0037239 ]
 [ 0.          0.          0.61466917  0.00548063]
 [ 0.          0.          0.          0.39226034]]


In [55]:
Q, R = factorize(A)

In [56]:
np.allclose(A[:4,:], np.dot(Q[:4,:],R))

True

일단 생각한 건 거짓이고, 그거 말고도 하나더 생각한거 있는데 이거는 수학자체에서 막혀서 교수님의 도움이 필요할 듯